### ISSUE TITLE
ssl problem

### ISSUE THREAD

**Issue by patrickGodin** [mikegogulski/python-otrxmppchannel#2]
Hi im trying to use your code but i have this error when execute. Im very new in python, need some help.

Here is the traceback : 

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/otrxmppchannel/connection.py", line 48, in run
    conntype = cl.connect()
  File "/usr/local/lib/python2.7/dist-packages/xmpp/client.py", line 205, in connect
    while not self.TLS.starttls and self.Process(1): pass
  File "/usr/local/lib/python2.7/dist-packages/xmpp/dispatcher.py", line 303, in dispatch
    handler['func'](session,stanza)
  File "/usr/local/lib/python2.7/dist-packages/xmpp/transports.py", line 337, in StartTLSHandler
    self._startSSL()
  File "/usr/local/lib/python2.7/dist-packages/xmpp/transports.py", line 316, in _startSSL
    tcpsock._sslIssuer = tcpsock._sslObj.issuer()
AttributeError: '_ssl._SSLSocket' object has no attribute 'issuer'

**Comment by mikegogulski** [comment]
I haven't looked at this code in years, but even if I had, it would be very hard to investigate what the trouble might be without seeing how you're invoking the library.

**Comment by patrickGodin** [comment]
Thanks for the quick reply

This is my code : 

```
import time
import ssl
from otrxmppchannel import OTRXMPPChannel
from otrxmppchannel.connection import OTR_TRUSTED, OTR_UNTRUSTED,OTR_UNENCRYPTED, OTR_UNKNOWN

# Load the base64-encoded OTR DSA key. Constructing the object without
# a key will generate one and provide it via ValueError exception.
privkey = open('cert.txt', 'r').read()

class MyOTRChannel(OTRXMPPChannel):
    def on_receive(self, message, from_jid, otr_state):
        if otr_state == OTR_TRUSTED:
            state = 'trusted'
        elif otr_state == OTR_UNTRUSTED:
            state = 'UNTRUSTED!'
        elif otr_state == OTR_UNENCRYPTED:
            state = 'UNENCRYPTED!'
        else:
            state = 'UNKNOWN OTR STATUS!'
        print('received %s from %s (%s)' % (message, from_jid, state))

mychan = MyOTRChannel(
    'myjid@serv',
    'pass',
    [
        'jid_receipt@serv',
        'another_jid_receipt@serv'
    ],
    privkey
)

mychan.send('')  # Force OTR setup
time.sleep(3)  # Wait a bit for OTR setup to complete
mychan.send('This message should be encrypted')
```

**Comment by patrickGodin** [comment]
to install the libraries i do 

$ pip install --pre xmpppy 
$ pip install otrxmppchannel

**Comment by mikegogulski** [comment]
It seems like you're using an older version of the xmppy library, which mine depends on. I found this commit which removed the reference to _sslObj.issuer():

https://github.com/normanr/xmpppy/commit/15854fc9941cedd78c0367be49f6c828e1c846c5#diff-a0cd58a08a1982f6d803f6bb1cc1ec72

Does that help at all?

**Comment by patrickGodin** [comment]
thank you it solves my problem,  i dont have error anymore and jabber conversation opens and seem like otr is launched but i dont receive any message. thank you for help

**Comment by patrickGodin** [comment]
i just receive the message if the sender is in my contact list. How can i receive the message even if i dont have the receipter in my contact list

Thanks for help

**Comment by mikegogulski** [comment]
Glad to hear you got it working.

Unfortunately, communicating with senders not already in your contact list is a use case I didn't consider when developing the library.
